local blessCurseManagerApi = require("chaosbag/BlessCurseManagerApi")
local playermatApi         = require("playermat/PlayermatApi")

function onLoad()
  self.addContextMenuItem("Enable menus", addSealingMenus)
end

function addSealingMenus(playerColor)
  self.clearContextMenu()
  for _, obj in ipairs(playermatApi.getUsedInvestigatorCards()) do
    blessCurseManagerApi.addBlurseSealingMenu(playerColor, obj, true)
  end
end
