VALID_TOKENS = {
  ["Elder Sign"] = true
}

require("playercards/CardsThatSealTokens")

local playmatApi = require("playermat/PlaymatApi")
local guidReferenceApi = require("core/GUIDReferenceApi")
local chaosBagApi      = require("chaosbag/ChaosBagApi")
local contextMenuAdded

function onCollisionEnter()
  if contextMenuAdded then return end
  contextMenuAdded = true
  self.addContextMenuItem("Resolve Elder Sign", resolveSealed)
end

function resolveSealed()
    if #sealedTokens == 0 then
      broadcastToAll("No tokens sealed.", "Red")
      return
    end
    local closestMatColor = playmatApi.getMatColorByPosition(self.getPosition())
    local mat = guidReferenceApi.getObjectByOwnerAndType(closestMatColor, "Playermat")
    guidToBeResolved = table.remove(sealedTokens)
    chaosBagApi.drawChaosToken(mat, true, _, guidToBeResolved)
end