---------------------------------------------------------
-- specific setup (different for each playmat)
---------------------------------------------------------

PLAY_ZONE_POSITION    = { x = -54.5, y = 4, z = -19 }
PLAY_ZONE_SCALE       = { x = 32, y = 5, z = 12 }
TRASHCAN_GUID         = "f7b6c8"
STAT_TRACKER_GUID     = "b4a5f7"
RESOURCE_COUNTER_GUID = "816d84"
CLUE_COUNTER_GUID     = "1769ed"
CLUE_CLICKER_GUID     = "3f22e5"

require("playermat/Playmat")
