---------------------------------------------------------
-- specific setup (different for each playmat)
---------------------------------------------------------

PLAYER_COLOR          = "Green"
PLAY_ZONE_POSITION    = { x = -26.5, y = 4, z = 26.5 }
PLAY_ZONE_SCALE       = { x = 32, y = 5, z = 12 }
TRASHCAN_GUID         = "5f896a"
STAT_TRACKER_GUID     = "af7ed7"
RESOURCE_COUNTER_GUID = "cd15ac"
CLUE_COUNTER_GUID     = "032300"
CLUE_CLICKER_GUID     = "891403"

require("playermat/Playmat")
