---------------------------------------------------------
-- specific setup (different for each playmat)
---------------------------------------------------------

PLAY_ZONE_POSITION    = { x = -26.5, y = 4, z = -26.5 }
PLAY_ZONE_SCALE       = { x = 32, y = 5, z = 12 }
TRASHCAN_GUID         = "4b8594"
STAT_TRACKER_GUID     = "e74881"
RESOURCE_COUNTER_GUID = "a4b60d"
CLUE_COUNTER_GUID     = "37be78"
CLUE_CLICKER_GUID     = "4111de"

require("playermat/Playmat")
