---------------------------------------------------------
-- specific setup (different for each playmat)
---------------------------------------------------------

PLAY_ZONE_POSITION    = { x = -54.5, y = 4, z = 19 }
PLAY_ZONE_SCALE       = { x = 32, y = 5, z = 12 }
TRASHCAN_GUID         = "147e80"
STAT_TRACKER_GUID     = "e598c2"
RESOURCE_COUNTER_GUID = "4406f0"
CLUE_COUNTER_GUID     = "d86b7c"
CLUE_CLICKER_GUID     = "db85d6"

require("playermat/Playmat")
