-- Customizable Cards: Damning Testimony

-- Color information for buttons
boxSize = 40

-- static values
x_1         = -0.935
x_offset    = 0.075

-- z-values (lines on the sheet)
posZ = {
    -0.925,
    -0.475,
    -0.25,
    -0.01,
    0.428,
    0.772
}

-- box setup (amount of boxes per line and amount of marked boxes in that line)
existingBoxes = { 1, 2, 2, 3, 3, 4 }
inputBoxes = {}

require("playercards/customizable/UpgradeSheetLibrary")
