-- Customizable Cards: Empirical Hypothesis

-- Color information for buttons
boxSize = 37

-- static values
x_1         = -0.935
x_offset    = 0.069

-- z-values (lines on the sheet)
posZ = {
    -0.905,
    -0.7,
    -0.505,
    -0.3,
    -0.09,
    0.3,
    0.592,
    0.888
}

-- box setup (amount of boxes per line and amount of marked boxes in that line)
existingBoxes = { 1, 1, 1, 1, 2, 2, 3, 4 }
inputBoxes = {}

require("playercards/customizable/UpgradeSheetLibrary")
