-- Customizable Cards: Hunter's Armor

-- Color information for buttons
boxSize = 40

-- static values
x_1         = -0.933
x_offset    = 0.075

-- z-values (lines on the sheet)
posZ = {
    -0.892,
    -0.560,
    -0.220,
    -0.092,
    0.047,
    0.376,
    0.820
}

-- box setup (amount of boxes per line and amount of marked boxes in that line)
existingBoxes = { 1, 2, 2, 2, 2, 3, 3 }
inputBoxes = {}

require("playercards/customizable/UpgradeSheetLibrary")
