-- Customizable Cards: Hyperphysical Shotcaster

-- Color information for buttons
boxSize = 38

-- static values
x_1         = -0.935
x_offset    = 0.069

-- z-values (lines on the sheet)
posZ = {
    -0.9,
    -0.615,
    -0.237,
    0.232,
    0.61,
    0.988,
    1.185
}

-- box setup (amount of boxes per line and amount of marked boxes in that line)
existingBoxes = { 2, 2, 2, 2, 2, 4, 4 }
inputBoxes = {}

require("playercards/customizable/UpgradeSheetLibrary")
