-- Customizable Cards: Makeshift Trap

-- Color information for buttons
boxSize = 39

-- static values
x_1         = -0.935
x_offset    = 0.0735

-- z-values (lines on the sheet)
posZ = {
    -0.889,
    -0.655,
    -0.325,
    -0.085,
    0.252,
    0.585,
    0.927
}

-- box setup (amount of boxes per line and amount of marked boxes in that line)
existingBoxes = { 1, 1, 2, 2, 2, 3, 4 }
inputBoxes = {}

require("playercards/customizable/UpgradeSheetLibrary")
