-- Customizable Cards: Pocket Multi Tool

-- Color information for buttons
boxSize = 40

-- static values
x_1         = -0.933
x_offset    = 0.075

-- z-values (lines on the sheet)
posZ = {
    -0.892,
    -0.560,
    -0.326,
    -0.092,
    0.142,
    0.376,
    0.610
}

-- box setup (amount of boxes per line and amount of marked boxes in that line)
existingBoxes = { 1, 1, 2, 2, 2, 3, 4 }
inputBoxes = {}

require("playercards/customizable/UpgradeSheetLibrary")
