-- Customizable Cards: Runic Axe

-- Color information for buttons
boxSize = 38

-- static values
x_1         = -0.935
x_offset    = 0.0705

-- z-values (lines on the sheet)
posZ = {
    -0.92,
    -0.715,
    -0.415,
    -0.018,
    0.265,
    0.66,
    0.86,
    1.065
}

-- box setup (amount of boxes per line and amount of marked boxes in that line)
existingBoxes = { 1, 1, 1, 1, 1, 3, 3, 4 }
inputBoxes = {}

require("playercards/customizable/UpgradeSheetLibrary")
