---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Whimsical.
--- DateTime: 2021-08-05 6:51 p.m.
---

---@param name string
---@param image string
---@return ChaosToken
local MakeToken = function (name, image)
    return {
        name = name,
        image = image
    }
end

sources = {
    [1] = MakeToken("+1", "https://i.imgur.com/uIx8jbY.png"),
    [0] = MakeToken("0", "https://i.imgur.com/btEtVfd.png"),
    [-1] = MakeToken("-1", "https://i.imgur.com/w3XbrCC.png"),
    [-2] = MakeToken("-2", "https://i.imgur.com/bfTg2hb.png"),
    [-3] = MakeToken("-3", "https://i.imgur.com/yfs8gHq.png"),
    [-4] = MakeToken("-4", "https://i.imgur.com/qrgGQRD.png"),
    [-5] = MakeToken("-5", "https://i.imgur.com/3Ym1IeG.png"),
    [-6] = MakeToken("-6", "https://i.imgur.com/c9qdSzS.png"),
    [-7] = MakeToken("-7", "https://i.imgur.com/4WRD42n.png"),
    [-8] = MakeToken("-8", "https://i.imgur.com/9t3rPTQ.png"),
    ["s"] = MakeToken("Skull", "https://i.imgur.com/stbBxtx.png"),
    ["c"] = MakeToken("Cultist", "https://i.imgur.com/VzhJJaH.png"),
    ["t"] = MakeToken("Tablet", "https://i.imgur.com/1plY463.png"),
    ["e"] = MakeToken("Elder Thing", "https://i.imgur.com/ttnspKt.png"),
    ["*"] = MakeToken("Elder Sign", "https://i.imgur.com/nEmqjmj.png"),
    ["f"] = MakeToken("Auto-fail", "https://i.imgur.com/lns4fhz.png"),
    ["+"] = MakeToken("Bless", "http://cloud-3.steamusercontent.com/ugc/1655601092778627699/339FB716CB25CA6025C338F13AFDFD9AC6FA8356/"),
    ["-"] = MakeToken("Curse", "http://cloud-3.steamusercontent.com/ugc/1655601092778636039/2A25BD38E8C44701D80DD96BF0121DA21843672E/"),
    ["fr"] = MakeToken("Frost", "http://cloud-3.steamusercontent.com/ugc/1858293462583104677/195F93C063A8881B805CE2FD4767A9718B27B6AE/"),
}
