-- card backs
CARD_BACK_URL            = {
  ScenarioCard =
  "https://steamusercontent-a.akamaihd.net/ugc/2342503777940351785/F64D8EFB75A9E15446D24343DA0A6EEF5B3E43DB/",
  PlayerCard =
  "https://steamusercontent-a.akamaihd.net/ugc/2342503777940352139/A2D42E7E5C43D045D72CE5CFC907E4F886C8C690/"
}

-- chaos token data
ID_URL_MAP               = {
  ['blue']    = { name = "Elder Sign", url = 'https://steamusercontent-a.akamaihd.net/ugc/12752993084999766477/F51D1B318EEBDD1E4B134C6E29A4636EC525D944/' },
  ['p1']      = { name = "+1", url = 'https://steamusercontent-a.akamaihd.net/ugc/10597496404609555263/F826E07708AFAB46ED98662578CAAF8296FA5834/' },
  ['0']       = { name = "0", url = 'https://steamusercontent-a.akamaihd.net/ugc/13269670021408345158/EF69E9EC26E086D285A065522359B524B40442D7/' },
  ['m1']      = { name = "-1", url = 'https://steamusercontent-a.akamaihd.net/ugc/12697778115542134876/394695C4F8BB7A10CE25A8BCE89A3CA1E1F47377/' },
  ['m2']      = { name = "-2", url = 'https://steamusercontent-a.akamaihd.net/ugc/10354261515494662814/F053E52F82FAC149907170F75044533F4AE7A96B/' },
  ['m3']      = { name = "-3", url = 'https://steamusercontent-a.akamaihd.net/ugc/10495647562658286398/F5076FB80B51B6CA0F287708629394609B8A985C/' },
  ['m4']      = { name = "-4", url = 'https://steamusercontent-a.akamaihd.net/ugc/12544334474795006833/6F7EAA17C3DEECD12E89C58B4840BA97D160923F/' },
  ['m5']      = { name = "-5", url = 'https://steamusercontent-a.akamaihd.net/ugc/10616800333184481829/77ABC38632F4323A98D584C1581F8D4F2C2AA8AC/' },
  ['m6']      = { name = "-6", url = 'https://steamusercontent-a.akamaihd.net/ugc/17089984339651120943/1260A0D66CA9AD42BE2FE22D9F63B0C62199F75C/' },
  ['m7']      = { name = "-7", url = 'https://steamusercontent-a.akamaihd.net/ugc/11060994120667187760/40129C4660CF74A0CB04A5E66E5745AE165DEF64/' },
  ['m8']      = { name = "-8", url = 'https://steamusercontent-a.akamaihd.net/ugc/16236106719980464434/3DF0665924CBA1D1550399780AE0E137AE353BF6/' },
  ['skull']   = { name = "Skull", url = 'https://steamusercontent-a.akamaihd.net/ugc/16524819880129816282/33E39A412180CE0D05A9F1371FE831B0137E3FB7/' },
  ['cultist'] = { name = "Cultist", url = 'https://steamusercontent-a.akamaihd.net/ugc/16921402067936329643/88BAD3E7176FB37DE0AA57B13E2F6BF037BA3AAC/' },
  ['tablet']  = { name = "Tablet", url = 'https://steamusercontent-a.akamaihd.net/ugc/12273114594379564576/5A2FB9153BF832189D8F55445A81CB882EE262A6/' },
  ['elder']   = { name = "Elder Thing", url = 'https://steamusercontent-a.akamaihd.net/ugc/12752993084999766477/F51D1B318EEBDD1E4B134C6E29A4636EC525D944/' },
  ['red']     = { name = "Auto-fail", url = 'https://steamusercontent-a.akamaihd.net/ugc/13462713915355299034/0494D15CB80BA2350FB3F776A2F3D98522184D4C/' },
  ['bless']   = { name = "Bless", url = 'https://steamusercontent-a.akamaihd.net/ugc/15633995627064781302/05298832BFA659FD2A8CA667B5AC9FFEE60ACA55/' },
  ['curse']   = { name = "Curse", url = 'https://steamusercontent-a.akamaihd.net/ugc/11040540336215346217/0EC0B73AA734FAD20994A8E53FC7033E4F107E41/' },
  ['frost']   = { name = "Frost", url = 'https://steamusercontent-a.akamaihd.net/ugc/14171305793640183838/33417C01030678C6432A7336B3DC1F1179E69943/' }
}

-- online functionality related variables
MOD_VERSION              = "4.2.1"
SOURCE_REPO              = "https://github.com/Chr1Z93/SCED-downloads/releases/latest/download/"
--SOURCE_REPO            = "https://github.com/Chr1Z93/SCED-downloads/releases/download/v1.0.1/"

-- these can be loaded by right-clicking the option panel button
OPTION_PRESETS           = {
  Chr1Z = {
    changePlayAreaImage  = true,
    showAttachmentHelper = true,
    showDisplacementTool = true,
    showDrawButton       = true,
    showHandHelper       = true,
    showSearchAssistant  = true,
    useResourceCounters  = "custom"
  },
  Daniel = {
    showHandHelper      = true,
    showSearchAssistant = true
  },
  PBG = {
    showHandHelper      = true,
    showSearchAssistant = true,
    useClassTexture     = false
  },
  thedave = {
    changePlayAreaImage  = true,
    showAttachmentHelper = true,
    showDisplacementTool = true,
    showDrawButton       = true,
    showHandHelper       = true,
    showOneDamageHorror  = true,
    showSearchAssistant  = true,
    useClueClickers      = true,
    useResourceCounters  = "enabled"
  }
}

-- this can be used to load specific options onLoad()
LOAD_DEBUG_OPTION_PANEL  = false
DEBUG_OPTION_PANEL_STATE = {
  showSearchAssistant = true
}
