-- card backs
CARD_BACK_URL              = {
  ScenarioCard =
  "https://steamusercontent-a.akamaihd.net/ugc/2342503777940351785/F64D8EFB75A9E15446D24343DA0A6EEF5B3E43DB/",
  PlayerCard =
  "https://steamusercontent-a.akamaihd.net/ugc/2342503777940352139/A2D42E7E5C43D045D72CE5CFC907E4F886C8C690/"
}

-- chaos token data
ID_URL_MAP                 = {
  ['blue']    = { name = "Elder Sign", url = 'https://i.imgur.com/nEmqjmj.png' },
  ['p1']      = { name = "+1", url = 'https://i.imgur.com/uIx8jbY.png' },
  ['0']       = { name = "0", url = 'https://i.imgur.com/btEtVfd.png' },
  ['m1']      = { name = "-1", url = 'https://i.imgur.com/w3XbrCC.png' },
  ['m2']      = { name = "-2", url = 'https://i.imgur.com/bfTg2hb.png' },
  ['m3']      = { name = "-3", url = 'https://i.imgur.com/yfs8gHq.png' },
  ['m4']      = { name = "-4", url = 'https://i.imgur.com/qrgGQRD.png' },
  ['m5']      = { name = "-5", url = 'https://i.imgur.com/3Ym1IeG.png' },
  ['m6']      = { name = "-6", url = 'https://i.imgur.com/c9qdSzS.png' },
  ['m7']      = { name = "-7", url = 'https://i.imgur.com/4WRD42n.png' },
  ['m8']      = { name = "-8", url = 'https://i.imgur.com/9t3rPTQ.png' },
  ['skull']   = { name = "Skull", url = 'https://i.imgur.com/stbBxtx.png' },
  ['cultist'] = { name = "Cultist", url = 'https://i.imgur.com/VzhJJaH.png' },
  ['tablet']  = { name = "Tablet", url = 'https://i.imgur.com/1plY463.png' },
  ['elder']   = { name = "Elder Thing", url = 'https://i.imgur.com/ttnspKt.png' },
  ['red']     = { name = "Auto-fail", url = 'https://i.imgur.com/lns4fhz.png' },
  ['bless']   = { name = "Bless", url = 'https://steamusercontent-a.akamaihd.net/ugc/1655601092778627699/339FB716CB25CA6025C338F13AFDFD9AC6FA8356/' },
  ['curse']   = { name = "Curse", url = 'https://steamusercontent-a.akamaihd.net/ugc/1655601092778636039/2A25BD38E8C44701D80DD96BF0121DA21843672E/' },
  ['frost']   = { name = "Frost", url = 'https://steamusercontent-a.akamaihd.net/ugc/1858293462583104677/195F93C063A8881B805CE2FD4767A9718B27B6AE/' }
}

-- online functionality related variables
MOD_VERSION                = "4.2.0"
SOURCE_REPO                = "https://github.com/Chr1Z93/SCED-downloads/releases/latest/download/"
--SOURCE_REPO              = "https://github.com/Chr1Z93/SCED-downloads/releases/download/v1.0.1/"

-- these can be loaded by right-clicking the option panel button
OPTION_PRESETS             = {
  Chr1Z = {
    changePlayAreaImage  = true,
    showAttachmentHelper = true,
    showCleanUpHelper    = true,
    showDisplacementTool = true,
    showDrawButton       = true,
    showHandHelper       = true,
    showSearchAssistant  = true,
    useResourceCounters  = "custom"
  },
  Daniel = {
    showHandHelper       = true,
    showSearchAssistant  = true
  },
  thedave = {
    changePlayAreaImage  = true,
    showAttachmentHelper = true,
    showCleanUpHelper    = true,
    showDisplacementTool = true,
    showDrawButton       = true,
    showHandHelper       = true,
    showOneDamageHorror  = true,
    showSearchAssistant  = true,
    useClueClickers      = true,
    useResourceCounters  = "enabled"
  },
  PBG = {
    showHandHelper       = true,
    showSearchAssistant  = true,
    useClassTexture      = false
  },
}

-- this can be used to load specific option onLoad()
LOAD_DEBUG_OPTION_PANEL    = false
DEBUG_OPTION_PANEL_STATE   = {
  showSearchAssistant = true
}
