-- card backs
CARD_BACK_URL            = {
  ScenarioCard =
  "https://steamusercontent-a.akamaihd.net/ugc/2342503777940351785/F64D8EFB75A9E15446D24343DA0A6EEF5B3E43DB/",
  PlayerCard =
  "https://steamusercontent-a.akamaihd.net/ugc/2342503777940352139/A2D42E7E5C43D045D72CE5CFC907E4F886C8C690/"
}

-- chaos token data
ID_URL_MAP               = {
  ['blue']    = { name = "Elder Sign", url = 'https://steamusercontent-a.akamaihd.net/ugc/14299675228001607884/DC8691C239014FE7DDABB886BB1D383C05DC490F/' },
  ['p1']      = { name = "+1", url = 'https://steamusercontent-a.akamaihd.net/ugc/10065518989680601262/55C6E20197F82A335B9B949CC01FCF6E9DC9B2B6/' },
  ['0']       = { name = "0", url = 'https://steamusercontent-a.akamaihd.net/ugc/10467636488768711896/65D31C09954BC6DD95A3EDB44AFF7B5CAC5DDFBC/' },
  ['m1']      = { name = "-1", url = 'https://steamusercontent-a.akamaihd.net/ugc/18141677772083355157/B6921FE2FF0BAD3A29117FFF917F1B214A0A1737/' },
  ['m2']      = { name = "-2", url = 'https://steamusercontent-a.akamaihd.net/ugc/16300603643773411041/2639335E189779A56EBB1DBD5770B879A72549C5/' },
  ['m3']      = { name = "-3", url = 'https://steamusercontent-a.akamaihd.net/ugc/12389435929210412458/FBA601FAAD79D9B70E4EB3E6F45A08E86DE1C09A/' },
  ['m4']      = { name = "-4", url = 'https://steamusercontent-a.akamaihd.net/ugc/11693498521773237474/7ECFB6071A5FC5D9B2530631C1C9BB913450AD69/' },
  ['m5']      = { name = "-5", url = 'https://steamusercontent-a.akamaihd.net/ugc/16829517245644419133/55CF59E1295D6CE0A2AAF69784BCE164D1D0F807/' },
  ['m6']      = { name = "-6", url = 'https://steamusercontent-a.akamaihd.net/ugc/16991160142031023290/288C4B755FC36B49C0FC5E5DB5929D9720932601/' },
  ['m7']      = { name = "-7", url = 'https://steamusercontent-a.akamaihd.net/ugc/18160465441183960058/EBE2A6876F2190F52BE318830A6A145AC6108D14/' },
  ['m8']      = { name = "-8", url = 'https://steamusercontent-a.akamaihd.net/ugc/17945201728310792736/3B17446B285B165E095F899C97CAB0DBD9D22C4A/' },
  ['skull']   = { name = "Skull", url = 'https://steamusercontent-a.akamaihd.net/ugc/15828862155539708736/BDAB049A331E3528626DA3B7CBA621F1846E472E/' },
  ['cultist'] = { name = "Cultist", url = 'https://steamusercontent-a.akamaihd.net/ugc/10819121326050938896/43990FCC095A8AE2C3398C7D67A6C068DA6A6749/' },
  ['tablet']  = { name = "Tablet", url = 'https://steamusercontent-a.akamaihd.net/ugc/17952552005967267216/05C897C573865E2513D8B08CD68D5ED5CC7E689C/' },
  ['elder']   = { name = "Elder Thing", url = 'https://steamusercontent-a.akamaihd.net/ugc/12269151051478770224/9D3E87A4406D441F8BACEAAE05A4215D57D4A36C/' },
  ['red']     = { name = "Auto-fail", url = 'https://steamusercontent-a.akamaihd.net/ugc/15030955895089669191/BC72E714C4DF998F1D0F5ED56AF267EBF949C215/' },
  ['bless']   = { name = "Bless", url = 'https://steamusercontent-a.akamaihd.net/ugc/17626656568141106343/AF58317B4B90FDBB2859D667717956A24F838F9E/' },
  ['curse']   = { name = "Curse", url = 'https://steamusercontent-a.akamaihd.net/ugc/16368291675628055072/CA7EF7D227D3BD3001A52D6D1EC40F631752270C/' },
  ['frost']   = { name = "Frost", url = 'https://steamusercontent-a.akamaihd.net/ugc/17407496234279022797/27E998B2DCB82BF6F2B544FF7C1A831048BE68F8/' }
}

-- online functionality related variables
MOD_VERSION              = "4.5.0"
SOURCE_REPO              = "https://github.com/Chr1Z93/SCED-downloads/releases/latest/download/"
--SOURCE_REPO            = "https://github.com/Chr1Z93/SCED-downloads/releases/download/v1.0.1/"

-- these sites are GitHub proxies to make content accessible in regions that don't have GitHub access
FALLBACK_MIRRORS = {
  "https://gh.llkk.cc/",
  "https://gh-proxy.com/"
}

-- these can be loaded by right-clicking the option panel button
OPTION_PRESETS           = {
  Chr1Z = {
    changePlayAreaImage  = true,
    highlightMinicards   = true,
    showAttachmentHelper = true,
    showDisplacementTool = true,
    showDrawButton       = true,
    showHandHelper       = true,
    showSearchAssistant  = true,
    skipTour             = true,
    tokenArrangerOdds    = "Full",
    useResourceCounters  = "custom",
    NavigationOverlay    = { pitch = 90, distance = 110 }
  },
  Daniel = {
    showAttachmentHelper = true,
    showHandHelper       = true,
    showSearchAssistant  = true,
    skipTour             = true,
    tokenArrangerOdds    = "Cumulative"
  },
  PBG = {
    showHandHelper      = true,
    showSearchAssistant = true,
    useClassTexture     = false
  },
  thedave = {
    changePlayAreaImage  = true,
    showAttachmentHelper = true,
    showDisplacementTool = true,
    showDrawButton       = true,
    showHandHelper       = true,
    showOneDamageHorror  = true,
    showSearchAssistant  = true,
    useClueClickers      = true,
    useResourceCounters  = "enabled"
  }
}

-- this can be used to load specific options onLoad()
LOAD_DEBUG_OPTION_PANEL  = false
DEBUG_OPTION_PANEL_STATE = {
  showSearchAssistant = true
}
