function onLoad()
  self.createButton({
    label = "Download",
    click_function = "buttonClick_download",
    function_owner = self,
    position = { 0, 0.1, 2.2 },
    height = 240,
    width = 800,
    font_size = 150,
    color = { 0, 0, 0 },
    font_color = { 1, 1, 1 }
  })
end

function buttonClick_download()
  Global.call('placeholder_download', { url = self.getGMNotes(), replace = self.guid })
end
