local searchLib       = require("util/SearchLib")
local tokenManagerApi = require("tokens/TokenManagerApi")

function onDrop()
  matchCardBelow()
end

function matchCardBelow()
  local searchResult = searchLib.belowPosition(self.getPosition(), "isCard")
  if #searchResult > 0 then
    local card = searchResult[1]
    local result = tokenManagerApi.addUseToCard(card, "resource")
    if result then
      Wait.time(function() self.destruct() end, 0.1)
    end
  end
end
